### ISSUE TITLE
Opera gx has a problem with a line

### ISSUE THREAD

**Issue by Hearts29** [sicarii-13/Facebook-Container-for-Opera#1]
![image](https://user-images.githubusercontent.com/80163139/111864281-6399bd00-8979-11eb-9448-5006ef964bec.png)

Hi,
I downloaded Facebook container on Github Desktop then loaded it into Opera GX LVL2 (core: 73.0.3856.415). Is this normal ? It seems to work fine.

**Comment by jd-rk9** [comment]
No this should not cause any issues, but I also don't maintain this at all at the moment. I based this on the mozzilla published plugin and ported it to Opera, wasn't much work. It isn't something I have seen last time I used it.
